.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
CODE_OF_CONDUCT.md

Added Code of Conduct.
N/A
- [!] My changes generate no new warnings

Created Code of Conduct

---

src/app/api/alloy/[alloyName]/route.ts
src/app/api/alloy/route.ts
src/app/components/AlloyComponentDisplay.tsx
src/app/components/AlloySelectionGrid.tsx

Cleaned up and simplified code.
Split the main API into two different paths. In addition to that, updated the paths of the API to be more consistent.

API Cleanup

---

.github/ISSUE_TEMPLATE/config.yaml

Added issue template configuration.
N/A

Update Issue Template

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Update Issue Title

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Update Issue Labels

---

.github/WORKFLOWS/run-tests.yml
jest.config.ts
package-lock.json
package.json
sonar-project.properties
src/app/api/alloy/[alloyName]/minerals/route.ts
test/app/api/[alloyName]/minerals/route.test.ts
test/app/api/[alloyName]/route.test.ts
test/app/api/route.test.ts
tsconfig.json

Jest Setup

---

.github/workflows/run-tests.yml

Added cache mechanism to GitHub action. Updated directory name to lowercase to ensure it is picked up by GitHub.
N/A

Updated GitHub Action

---

.github/workflows/run-tests.yml
jest.config.ts
src/app/api/alloy/[alloyName]/minerals/route.ts
src/app/functions/algorithm.ts
src/app/types/index.ts
test/app/api/[alloyName]/minerals/route.test.ts
test/app/functions/algorithm.test.ts
tsconfig.json

Created algorithm for determining required inputs and viability.
Unit tests for basic acceptance criteria were made.
The alloy mineral endpoint has been updated to be more flattened to work better with the algorithm structure.

Created algorithm for determining required inputs and viability.

---

.github/README.md

Fixed the reference pointing to the separate branch.
N/A

Update License Reference

---

src/app/components/AlloyComponentDisplay.tsx
src/app/components/MineralAccordion.tsx
src/app/globals.css

Created the base input and output on the frontend.

Input & Output Frontend

---

src/app/components/AlloyComponentDisplay.tsx
src/app/components/Error.tsx

Split out error component for re-usability and clarity.

Split Error Component

---

src/app/components/Error.tsx

Fixed shortcomings of the new ErrorComponent as caught by CI/CD pipeline.
Shortcommings caught by sonar cloud.

Error Component Enhancements

---

src/app/components/MineralAccordion.tsx

Cleanup of miscelaneous CI detected issues.

Code Cleanup

---

src/app/components/AlloyComponentDisplay.tsx
src/app/components/AlloySelectionGrid.tsx
src/app/components/MineralAccordion.tsx
src/app/globals.css
src/app/page.tsx

Quality of life updates:
- Changed of colour scheme
- Improved input flow
- Improved clarity and constraints
- Minor code cleanup
N/A

Quality of Life Updates

---

src/app/components/AlloyComponentDisplay.tsx
src/app/components/ErrorComponent.tsx
src/app/data/alloys.json
src/app/functions/utils.ts
src/app/types/index.ts

Added ingots & nuggets to list display, with the default assumption that an ingot & nugget exists, unless overriden.
Added an error display when fetch errors occur.

Added ingots & nuggets to list display

---

src/app/components/AlloyComponentDisplay.tsx

Added console log to error prop, to ensure the bugs can be fixed where applicalbe.
Tested locally by reproducing a bug.

Added Console Log to Error

---

src/app/components/AlloyComponentDisplay.tsx

Fixed "Calculate" Button not updating due to calculation starting immediately.
Tested Locally on FE.

Fixed INP Issue with "Calculate" Button

---

src/app/api/alloy/[alloyName]/minerals/route.ts

Fixed deprecation warning related to `api/alloy/[alloyName]/minerals/route.ts`
Tested locally on dev.

Fixed Default Export Deprecation Warning in Dev & Prod

---

.github/README.md

Updated upstream link in README.md.
N/A

Updated Upstream Link

---

package-lock.json

Bumped cross-spawn 7.0.3 => 7.0.6 (high DDoS vulnerability).
Developmen build

Bump cross-spawn

---

eslint.config.mjs
next-sitemap.config.js
next.config.mjs
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
postcss.config.mjs
public/robots.txt
public/sitemap-0.xml
src/app/[type]/[id]/[version]/[metal]/page.tsx
src/app/[type]/[id]/[version]/layout.tsx
src/app/api/[type]/[id]/[version]/metal/[metal]/route.ts
src/components/MineralAccordion.tsx
src/styles/globals.css

- Bumped dependencies.
- Bumped to TailwindCSS 4.

Bump Dependencies

---

next.config.mjs

Old links, such as bookmarked or history URLs no longer work. This change provides compatibility by redirecting anyone with old URLs to the new URL.
Potentially a notification banner of some form could be worthwhile.

Added Redirect System

---

src/data/gameversions.json
src/data/modpack/terrafirmagreg/1.20.x_0.10.x/minerals.json
src/data/modpack/terrafirmagreg/1.20.x_0.10.x/outputs.json
src/data/modpack/terrafirmagreg/1.20.x_0.7.x/outputs.json
src/data/modpack/terrafirmagreg/1.20.x_0.9.x/outputs.json

Added new 0.10 ores and set default ingot value across all TFG versions
Tested manually

TFG 0.10 Support

---

src/components/MetalComponentDisplay.tsx

Fixed issue where changing the desired input target would change the output box information with unreasonable information. Transitively fixed issue with poor rounding.
Manually tested.

Fixed Output Type Change Based on Input Change

---

src/app/[type]/[id]/[version]/metals/page.tsx
src/components/FilterBar.tsx
src/functions/keyboardDetection.ts

Mobile devices still show keyboard shortcuts, which is confusing to the users.
Manually tested.

Physical Keyboard Check for UI elements

---

package.json

Removed package version since this project is versioned by HashVer principles. Also fixed naming to be consistent after rename.
N/A

Update Package Information

---

src/components/HeadingWithBackButton.tsx

Fix react hook dependency error.
No logic changed: N/A

Fix dependency warning
